<?php

/**  
* To create button(Store Walk in) under the Store walk in menu 
* @category: PHTML
* @package: Visionet/CustomerNotification
* @copyright: Visionet Systems Limited. All rights reserved.
* @license: Visionet Systems Limited
* @author: Nikhil A <nikhil.a@visionetsystems.com>
* @keywords: Module Visionet_CustomerNotification
*/

use Visionet\HelloWorld\Block\Index ; 

$blockObj= $block->getLayout()->createBlock('Visionet\CustomerNotification\Block\Index');

?>
<label><?= __("Dear customer,Please click on the button to register into store.") ?></label>
<br>
<br>
<form method="post" action="<?= $blockObj->getPostUrlFunction() ?>">
  
    <input type="submit" value="<?= __("Walk in") ?>" class="button"/>
                  
</form>


<style>
.button{
    height:50px;
    width:100px;
    font-size:20px;
    font-weight:bold;
    color:rgb(255,255,255);
    background:rgb(0,0,255);
    border-radius:10px;
    border:none;
    
}

.button:hover{
    background:rgb(255,0,0);
    border:none;
}

</style>
